language: python

python:
  - "2.7"

branches:
  only:
    - master

install:
  - pip install ansible

script:
  - ansible-playbook -u root -i ansible/inventories/production --private-key $pkey ansible/site.yml -e docker_password=$docker_password

addons:
  ssh_knows_hosts:
    - 165.22.146.95
