version: '3.4'

services:
  nginx:
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/avantysuniversity.nl/nginx:/etc/nginx/temp
      - /var/www/letsencrypt:/var/www/letsencrypt
    environment:
      - server_name=${server_name}
      - hsts_max_time=3000000
  webapi:
    image: "avantys/webapi:${DOCKER_TAG}"
