version: '3.5'

volumes:
  development_ssl: ~

services:
  nginx:
    environment:
      - server_name=avantysuniversity.nl
      - hsts_max_time=0m
    volumes:
      - development_ssl:/etc/letsencrypt/live/avantysuniversity.nl
      - ./nginx:/etc/nginx/temp

  webapi:
    build:
      context: ../
      dockerfile: docker/webapi/Dockerfile
    environment:
      - RABBITMQ_USER=avantys
      - RABBITMQ_PASS=c8ggRaQUwtBBiC6nW

  main-broker:
    environment:
      - RABBITMQ_DEFAULT_USER=avantys
      - RABBITMQ_DEFAULT_PASS=c8ggRaQUwtBBiC6nW

  ssl:
    build:
      context: ssl-dev
    volumes:
      - development_ssl:/ssl
