version: '3.4'

volumes:
  development_ssl: ~

services:
  nginx:
    environment:
      - server_name=avantysuniversity.nl
      - hsts_max_time=0m
    volumes:
      - development_ssl:/etc/letsencrypt/live/avantysuniversity.nl
      - ./nginx:/etc/nginx/temp
  webapi:
    build:
      context: ../
      dockerfile: docker/webapi/Dockerfile            
  ssl:
    build:
      context: ssl-dev
    volumes:
      - development_ssl:/ssl
