version: '3.5'

volumes:
  development_ssl: ~

services:
  nginx:
    environment:
      - server_name=avantysuniversity.nl
      - hsts_max_time=0m
    volumes:
      - development_ssl:/etc/letsencrypt/live/avantysuniversity.nl
      - ./nginx:/etc/nginx/temp

  webapi:
    build:
      context: ../
      dockerfile: docker/webapi/Dockerfile
    volumes:
      - ../src/webapi:/srv/html

  main-broker:
    environment:
      - RABBITMQ_DEFAULT_USER=avantys
      - RABBITMQ_DEFAULT_PASS=c8ggRaQUwtBBiC6nW

  ssl:
    build:
      context: ssl-dev
    volumes:
      - development_ssl:/ssl

  guiding_students:
    volumes:
      - ../src/guiding_students:/app
    user: "1000"
    command: ["/bin/sh", "-c", "npm install && node /app/node_modules/nodemon/bin/nodemon.js --legacy-watch index.js"]
    working_dir: /app
    environment:
      - MONGODB_PASSWORD=avantys123
      - RABBITMQ_PASS=c8ggRaQUwtBBiC6nW
    build:
      context: ../
      dockerfile: docker/guiding_students/Dockerfile

  guiding_students_db:
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=avantys123

  recruiting:
    volumes:
      - ../src/recruiting:/app
    user: "1000"
    command: ["/bin/sh", "-c", "npm install && node /app/node_modules/nodemon/bin/nodemon.js --legacy-watch index.js"]
    working_dir: /app
    environment:
      - MONGODB_PASSWORD=avantys123
      - RABBITMQ_PASS=c8ggRaQUwtBBiC6nW
    build:
      context: ../
      dockerfile: docker/recruiting/Dockerfile

  recruiting_db:
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=avantys123

  scheduling:
    volumes:
      - ../src/scheduling:/app
    user: "1000"
    command: ["/bin/sh", "-c", "npm install && node /app/node_modules/nodemon/bin/nodemon.js --legacy-watch index.js"]
    working_dir: /app
    environment:
      - MONGODB_PASSWORD=avantys123
      - RABBITMQ_PASS=c8ggRaQUwtBBiC6nW
    build:
      context: ../
      dockerfile: docker/scheduling/Dockerfile

  scheduling_db:
    ports:
      - 27019:27017
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=avantys123

  student_administration:
    volumes:
      - ../src/student_administration:/app
    user: "1000"
    command: ["/bin/sh", "-c", "npm install && node /app/node_modules/nodemon/bin/nodemon.js --legacy-watch index.js"]
    working_dir: /app
    environment:
      - MONGODB_PASSWORD=avantys123
      - RABBITMQ_PASS=c8ggRaQUwtBBiC6nW
    build:
      context: ../
      dockerfile: docker/student_administration/Dockerfile

  student_administration_db:
    ports:
      - 27020:27017
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=avantys123

  student_portal:
    volumes:
      - ../src/student_portal:/app
    user: "1000"
    command: ["/bin/sh", "-c", "npm install && node /app/node_modules/nodemon/bin/nodemon.js --legacy-watch index.js"]
    working_dir: /app
    environment:
      - MONGODB_PASSWORD=avantys123
      - RABBITMQ_PASS=c8ggRaQUwtBBiC6nW
    build:
      context: ../
      dockerfile: docker/student_portal/Dockerfile

  student_portal_db:
    ports:
      - 27021:27017
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=avantys123

  evaluating_students:
    volumes:
      - ../src/evaluating_students:/app
    user: "1000"
    command: ["/bin/sh", "-c", "npm install && node /app/node_modules/nodemon/bin/nodemon.js --legacy-watch index.js"]
    working_dir: /app
    environment:
      - MONGODB_PASSWORD=avantys123
      - RABBITMQ_PASS=c8ggRaQUwtBBiC6nW
    build:
      context: ../
      dockerfile: docker/evaluating_students/Dockerfile
  
  evaluating_students_db:
    ports:
      - 27022:27017
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=avantys123

