version: '3.4'

networks:
  nginx: ~

services:
  nginx:
    image: nginx:1.15.12-alpine
    restart: always
    networks:
      - nginx
    ports:
      - 80:8000
      - 443:8081
    command: ["/bin/sh", "-c", "rm -rf /var/cache/nginx/*
      && rm -rfv /etc/nginx/conf.d/*
      && for i in $$(find /etc/nginx/temp/ | grep -F .conf); do awk '{while(match($$0,\"[$$]{[^}]*}\")) {var=substr($$0,RSTART+2,RLENGTH -3);gsub(\"[$$]{\"var\"}\",ENVIRON[var])}}1' < \"$$i\" > $$(echo $${i/temp//}); done
      && nginx -g 'daemon off;'"]