version: '3.5'

services:
  nginx:
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/avantysuniversity.nl/nginx:/etc/nginx/temp
      - /var/www/letsencrypt:/var/www/letsencrypt
    environment:
      - server_name=${server_name}
      - hsts_max_time=3000000

  webapi:
    image: "avantys/webapi:${docker_tag}"

  main-broker:
    image: "avantys/rabbitmq:${docker_tag}"
    environment:
      - RABBITMQ_DEFAULT_PASS=<<DOCKER-SECRET:RABBIT_MQ_PASSWORD>>
    secrets:
      - RABBIT_MQ_PASSWORD

  guiding_students:
    image: avantys/guiding_students:${docker_tag}
    environment:
      - MONGODB_PASSWORD=<<DOCKER-SECRET:GUIDING_STUDENTS_DB_PASSWORD>>
      - RABBITMQ_PASS=<<DOCKER-SECRET:RABBIT_MQ_PASSWORD>>
      - SWAGGER_BASE_URL=${server_name}/api/v1/guiding_students
    secrets:
      - RABBIT_MQ_PASSWORD
      - GUIDING_STUDENTS_DB_PASSWORD
  guiding_students_db:
    image: avantys/mongo:${docker_tag}
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=<<DOCKER-SECRET:GUIDING_STUDENTS_DB_PASSWORD>>
    secrets:
      - GUIDING_STUDENTS_DB_PASSWORD

  recruiting:
    image: avantys/recruiting:${docker_tag}
    environment:
      - MONGODB_PASSWORD=<<DOCKER-SECRET:RECRUITING_DB_PASSWORD>>
      - RABBITMQ_PASS=<<DOCKER-SECRET:RABBIT_MQ_PASSWORD>>
      - SWAGGER_BASE_URL=${server_name}/api/v1/recruiting
    secrets:
      - RABBIT_MQ_PASSWORD
      - RECRUITING_DB_PASSWORD
  recruiting_db:
    image: avantys/mongo:${docker_tag}
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=<<DOCKER-SECRET:RECRUITING_DB_PASSWORD>>
    secrets:
      - RECRUITING_DB_PASSWORD
  audit:
    image: avantys/audit:${docker_tag}
    environment:
      - RABBITMQ_PASS=<<DOCKER-SECRET:RABBIT_MQ_PASSWORD>>
      - SWAGGER_BASE_URL=${server_name}/api/v1/audit
    secrets:
      - RABBIT_MQ_PASSWORD

  scheduling:
    image: avantys/scheduling:${docker_tag}
    environment:
      - MONGODB_PASSWORD=<<DOCKER-SECRET:SCHEDULING_DB_PASSWORD>>
      - RABBITMQ_PASS=<<DOCKER-SECRET:RABBIT_MQ_PASSWORD>>
      - SWAGGER_BASE_URL=${server_name}/api/v1/scheduling
    secrets:
      - RABBIT_MQ_PASSWORD
      - SCHEDULING_DB_PASSWORD
  scheduling_db:
    image: avantys/mongo:${docker_tag}
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=<<DOCKER-SECRET:SCHEDULING_DB_PASSWORD>>
    secrets:
      - SCHEDULING_DB_PASSWORD

  student_administration:
    image: avantys/student_administration:${docker_tag}
    environment:
      - MONGODB_PASSWORD=<<DOCKER-SECRET:STUDENT_ADMINISTRATION_DB_PASSWORD>>
      - RABBITMQ_PASS=<<DOCKER-SECRET:RABBIT_MQ_PASSWORD>>
      - SWAGGER_BASE_URL=${server_name}/api/v1/student_administration
    secrets:
      - RABBIT_MQ_PASSWORD
      - STUDENT_ADMINISTRATION_DB_PASSWORD
  student_administration_db:
    image: avantys/mongo:${docker_tag}
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=<<DOCKER-SECRET:STUDENT_ADMINISTRATION_DB_PASSWORD>>
    secrets:
      - STUDENT_ADMINISTRATION_DB_PASSWORD

  student_portal:
    image: avantys/student_portal:${docker_tag}
    environment:
      - MONGODB_PASSWORD=<<DOCKER-SECRET:STUDENT_PORTAL_DB_PASSWORD>>
      - RABBITMQ_PASS=<<DOCKER-SECRET:RABBIT_MQ_PASSWORD>>
      - SWAGGER_BASE_URL=${server_name}/api/v1/student_portal
    secrets:
      - RABBIT_MQ_PASSWORD
      - STUDENT_PORTAL_DB_PASSWORD
  student_portal_db:
    image: avantys/mongo:${docker_tag}
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=<<DOCKER-SECRET:STUDENT_PORTAL_DB_PASSWORD>>
    secrets:
      - STUDENT_PORTAL_DB_PASSWORD

  evaluating_students:
    image: avantys/evaluating_students:${docker_tag}
    environment:
      - MONGODB_PASSWORD=<<DOCKER-SECRET:EVALUATING_STUDENTS_DB_PASSWORD>>
      - RABBITMQ_PASS=<<DOCKER-SECRET:RABBIT_MQ_PASSWORD>>
      - SWAGGER_BASE_URL=${server_name}/api/v1/evaluating_students
    secrets:
      - RABBIT_MQ_PASSWORD
      - EVALUATING_STUDENTS_DB_PASSWORD
  evaluating_students_db:
    image: avantys/mongo:${docker_tag}
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=<<DOCKER-SECRET:EVALUATING_STUDENTS_DB_PASSWORD>>
    secrets:
      - EVALUATING_STUDENTS_DB_PASSWORD

  teacher_administration:
    image: avantys/teacher_administration:${docker_tag}
    environment:
      - MONGODB_PASSWORD=<<DOCKER-SECRET:TEACHER_ADMINISTRATION_DB_PASSWORD>>
      - RABBITMQ_PASS=<<DOCKER-SECRET:RABBIT_MQ_PASSWORD>>
      - SWAGGER_BASE_URL=${server_name}/api/v1/teacher_administration
    secrets:
      - RABBIT_MQ_PASSWORD
      - TEACHER_ADMINISTRATION_DB_PASSWORD
  teacher_administration_db:
    image: avantys/mongo:${docker_tag}
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=<<DOCKER-SECRET:TEACHER_ADMINISTRATION_DB_PASSWORD>>
    secrets:
      - TEACHER_ADMINISTRATION_DB_PASSWORD

  accounting:
    image: avantys/accounting:${docker_tag}
    environment:
      - MONGODB_PASSWORD=<<DOCKER-SECRET:ACCOUNTING_DB_PASSWORD>>
      - RABBITMQ_PASS=<<DOCKER-SECRET:RABBIT_MQ_PASSWORD>>
      - SWAGGER_BASE_URL=${server_name}/api/v1/accounting
    secrets:
      - RABBIT_MQ_PASSWORD
      - ACCOUNTING_DB_PASSWORD
  accounting_db:
    image: avantys/mongo:${docker_tag}
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=<<DOCKER-SECRET:ACCOUNTING_DB_PASSWORD>>
    secrets:
      - ACCOUNTING_DB_PASSWORD

secrets:
  RABBIT_MQ_PASSWORD:
    file: ${secrets_folder}/RABBIT_MQ_PASSWORD
  EVALUATING_STUDENTS_DB_PASSWORD:
    file: ${secrets_folder}/EVALUATING_STUDENTS_DB_PASSWORD
  STUDENT_PORTAL_DB_PASSWORD:
    file: ${secrets_folder}/STUDENT_PORTAL_DB_PASSWORD
  STUDENT_ADMINISTRATION_DB_PASSWORD:
    file: ${secrets_folder}/STUDENT_ADMINISTRATION_DB_PASSWORD
  SCHEDULING_DB_PASSWORD:
    file: ${secrets_folder}/SCHEDULING_DB_PASSWORD
  RECRUITING_DB_PASSWORD:
    file: ${secrets_folder}/RECRUITING_DB_PASSWORD
  GUIDING_STUDENTS_DB_PASSWORD:
    file: ${secrets_folder}/GUIDING_STUDENTS_DB_PASSWORD
  TEACHER_ADMINISTRATION_DB_PASSWORD:
    file: ${secrets_folder}/TEACHER_ADMINISTRATION_DB_PASSWORD
  ACCOUNTING_DB_PASSWORD:
    file: ${secrets_folder}/ACCOUNTING_DB_PASSWORD