version: '3.5'

services:
  nginx:
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/avantysuniversity.nl/nginx:/etc/nginx/temp
      - /var/www/letsencrypt:/var/www/letsencrypt
    environment:
      - server_name=${server_name}
      - hsts_max_time=3000000

  webapi:
    image: "avantys/webapi:${docker_tag}"
    environment:
      - RABBITMQ_USER=avantys
      - RABBITMQ_PASS=<<DOCKER-SECRET:RABBIT_MQ_PASSWORD>>
    secrets:
      - RABBIT_MQ_PASSWORD

  main-broker:
    environment:
      - RABBITMQ_DEFAULT_USER=avantys
      - RABBITMQ_DEFAULT_PASS_FILE=/run/secrets/RABBIT_MQ_PASSWORD
    secrets:
      - RABBIT_MQ_PASSWORD

  guiding_students:
    image: avantys/guiding_students:${docker_tag}
  recruiting:
    image: avantys/recruiting:${docker_tag}
  scheduling:
    image: avantys/scheduling:${docker_tag}
  student_administration:
    image: avantys/student_administration:${docker_tag}
  student_portal:
    image: avantys/student_portal:${docker_tag}
  evaluating_students:
    image: avantys/evaluating_students:${docker_tag}

secrets:
  RABBIT_MQ_PASSWORD:
    file: ${secrets_folder}/RABBIT_MQ_PASSWORD
