version: '3.5'

volumes:
  development_ssl: ~

services:
  nginx:
    environment:
      - server_name=avantysuniversity.nl
      - hsts_max_time=0m
    volumes:
      - development_ssl:/etc/letsencrypt/live/avantysuniversity.nl
      - ./nginx:/etc/nginx/temp

  webapi:
    build:
      context: ../
      dockerfile: docker/webapi/Dockerfile
    environment:
      - RABBITMQ_USER=avantys
      - RABBITMQ_PASS=c8ggRaQUwtBBiC6nW

  main-broker:
    environment:
      - RABBITMQ_DEFAULT_USER=avantys
      - RABBITMQ_DEFAULT_PASS=c8ggRaQUwtBBiC6nW

  ssl:
    build:
      context: ssl-dev
    volumes:
      - development_ssl:/ssl

  guiding_students:
    volumes:
      - ../guiding_students:/app
    ports:
      - 3000:3000
    command: ["/bin/sh", "-c", "npm install && node index.js"]
    working_dir: /app
    environment:
      - MONGODB_USERNAME=avantys
      - MONGODB_PASSWORD=avantys123
    build:
      context: ../
      dockerfile: docker/guiding_students/Dockerfile

  guiding_students_db:
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=avantys
      - MONGO_INITDB_ROOT_PASSWORD=avantys123
      - MONGO_INITDB_DATABASE=avantys

  recruiting:
    volumes:
      - ../recruiting:/app
    ports:
      - 3001:3000
    command: ["/bin/sh", "-c", "npm install && node index.js"]
    working_dir: /app
    environment:
      - MONGODB_USERNAME=avantys
      - MONGODB_PASSWORD=avantys123
    build:
      context: ../
      dockerfile: docker/recruiting/Dockerfile

  recruiting_db:
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=avantys
      - MONGO_INITDB_ROOT_PASSWORD=avantys123
      - MONGO_INITDB_DATABASE=avantys

  scheduling:
    volumes:
      - ../scheduling:/app
    ports:
      - 3002:3000
    command: ["/bin/sh", "-c", "npm install && node index.js"]
    working_dir: /app
    environment:
      - MONGODB_USERNAME=avantys
      - MONGODB_PASSWORD=avantys123
    build:
      context: ../
      dockerfile: docker/scheduling/Dockerfile

  scheduling_db:
    ports:
      - 27019:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=avantys
      - MONGO_INITDB_ROOT_PASSWORD=avantys123
      - MONGO_INITDB_DATABASE=avantys

  student_administration:
    volumes:
      - ../student_administration:/app
    ports:
      - 3003:3000
    command: ["/bin/sh", "-c", "npm install && node index.js"]
    working_dir: /app
    environment:
      - MONGODB_USERNAME=avantys
      - MONGODB_PASSWORD=avantys123
    build:
      context: ../
      dockerfile: docker/student_administration/Dockerfile

  student_administration_db:
    ports:
      - 27020:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=avantys
      - MONGO_INITDB_ROOT_PASSWORD=avantys123
      - MONGO_INITDB_DATABASE=avantys

  student_portal:
    volumes:
      - ../student_portal:/app
    ports:
      - 3004:3000
    command: ["/bin/sh", "-c", "npm install && node index.js"]
    working_dir: /app
    environment:
      - MONGODB_USERNAME=avantys
      - MONGODB_PASSWORD=avantys123
    build:
      context: ../
      dockerfile: docker/student_portal/Dockerfile

  student_portal_db:
    ports:
      - 27021:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=avantys
      - MONGO_INITDB_ROOT_PASSWORD=avantys123
      - MONGO_INITDB_DATABASE=avantys

  evaluating_students:
    volumes:
      - ../evaluating_students:/app
    ports:
      - 3005:3000
    command: ["/bin/sh", "-c", "npm install && node index.js"]
    working_dir: /app
    environment:
      - MONGODB_USERNAME=avantys
      - MONGODB_PASSWORD=avantys123
    build:
      context: ../
      dockerfile: docker/evaluating_students/Dockerfile
  
  evaluating_students_db:
    ports:
      - 27022:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=avantys
      - MONGO_INITDB_ROOT_PASSWORD=avantys123
      - MONGO_INITDB_DATABASE=avantys

