version: '3.5'

services:
  nginx:
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/avantysuniversity.nl/nginx:/etc/nginx/temp
      - /var/www/letsencrypt:/var/www/letsencrypt
    environment:
      - server_name=${server_name}
      - hsts_max_time=3000000

  webapi:
    image: "avantys/webapi:${docker_tag}"
    environment:
      - RABBITMQ_USER=avantys
      - RABBITMQ_PASS=<<DOCKER-SECRET:RABBIT_MQ_PASSWORD>>
    secrets:
      - RABBIT_MQ_PASSWORD

  main-broker:
    environment:
      - RABBITMQ_DEFAULT_USER=avantys
      - RABBITMQ_DEFAULT_PASS_FILE=/run/secrets/RABBIT_MQ_PASSWORD
    secrets:
      - RABBIT_MQ_PASSWORD

  guiding_students:
    image: node:11.15.0-alpine # TEMPONARY
  recruiting:
    image: node:11.15.0-alpine # TEMPONARY
  scheduling:
    image: node:11.15.0-alpine # TEMPONARY
  student_administration:
    image: node:11.15.0-alpine # TEMPONARY
  student_portal:
    image: node:11.15.0-alpine # TEMPONARY

secrets:
  RABBIT_MQ_PASSWORD:
    file: ${secrets_folder}/RABBIT_MQ_PASSWORD
