version: '3.5'

networks:
  nginx: ~
  broker: ~

services:
  nginx:
    image: nginx:1.15.12-alpine
    restart: always
    networks:
      - nginx
    ports:
      - 80:8080
      - 443:8081
    command: ["/bin/sh", "-c", "rm -rf /var/cache/nginx/*
      && rm -rfv /etc/nginx/conf.d/*
      && for i in $$(find /etc/nginx/temp/ | grep -F .conf); do awk '{while(match($$0,\"[$$]{[^}]*}\")) {var=substr($$0,RSTART+2,RLENGTH -3);gsub(\"[$$]{\"var\"}\",ENVIRON[var])}}1' < \"$$i\" > $$(echo $${i/temp//}); done
      && nginx -g 'daemon off;'"]

  webapi:
    restart: always
    networks:
     - nginx
     - broker
    expose:
     - 5000

  main-broker:
    image: rabbitmq:3.7.14-alpine
    networks:
      - broker
    hostname: main-broker

  guiding_students:
    expose:
      - 3000
    networks:
      - broker
  recruiting:
    expose:
      - 3000
    networks:
      - broker
  scheduling:
    expose:
      - 3000
    networks:
      - broker
  student_administration:
    expose:
      - 3000
    networks:
      - broker
  student_portal:
    expose:
      - 3000
    networks:
      - broker
