---
- name: Ensure vault secrets are set up locally
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: "Ensure ../../.avantys-vault folder exists"
      file:
        state: directory
        path: "../../.avantys-vault"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '700'

    - name: "Ensure vault secrets are in secret folder"
      copy:
        dest: "../../.avantys-vault/{{ item }}"
        content: "{{ docker_secrets[item] }}"
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"
        mode: '700'
      with_items: "{{ docker_secrets.keys() }}"
