---
- name: Build and publish
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: "Build images with tag {{ docker_tag }}"
      docker_image:
        path: "{{ item.path }}"
        dockerfile: "{{ item.dockerfile }}"
        name: "{{ item.name }}"
        tag: "{{ docker_tag }}"
        buildargs: "{{ item.buildargs }}"
      with_items: "{{ docker_images }}"
      tags: build_images

    - name: "Add latest tag to built images"
      docker_image:
        name: "{{ item.name }}:{{ docker_tag }}"
        repository: "{{ item.name }}:latest"
        pull: no
      with_items: "{{ docker_images }}"
      tags: build_images
      when: add_latest_tag

    - name: "Login to Docker registry as {{ docker_username }}"
      docker_login:
        username: "{{ docker_username }}"
        email: "{{ docker_email }}"
        password: "{{ docker_password }}"
      tags: publish_images

    - name: "Push tagged images to registry with tag {{ docker_tag }}"
      docker_image:
        name: "{{ item.name }}"
        tag: "{{ docker_tag }}"
        push: yes
      with_items: "{{ docker_images }}"
      tags: publish_images

    - name: "Push tagged images to registry with tag latest"
      docker_image:
        name: "{{ item.name }}"
        tag: "latest"
        push: yes
      with_items: "{{ docker_images }}"
      tags: publish_images
      when: add_latest_tag